# 2. Numpy 소개

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np

## 2.1. ndarray dtype

In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[0]

1

- python list와는 다른 data type

## 2.2. Universal function

In [7]:
# 기존 python list의 각 원소합 연산 과정

a = [1,2,3]
b = [4,5,6]

new_list = []
for e1, e2 in zip(a, b):
    new_list.append(e1 + e2)

new_list

[5, 7, 9]

In [10]:
# numpy를 활용한 각 원소합 연산 과정

a = np.array([1,2,3])
b = np.array([4,5,6])

#길이가 길어도 근사적으로 O(1)이 걸린다.
a+b

array([5, 7, 9])

In [13]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])